### ISSUE TITLE
Token Payment

### ISSUE THREAD

**Issue by devformatters** [thematters/developer-resource#125]
## Roadmap
- [Product doc](https://paper.dropbox.com/doc/Matters-USDT--BmP~kIHXkUnYYPNp4vlICRhWAg-hk1wXd1o4TXE86yGEsZTZ)

### Stage 1
- Design 

  - [x] https://github.com/thematters/developer-resource/issues/122
  
### Stage 2
- Implementations

  - [x] https://github.com/thematters/contracts/issues/107
  - [x] https://github.com/thematters/contracts/issues/108
  - [x] https://github.com/thematters/matters-server/issues/2696
  - [x] https://github.com/thematters/matters-server/issues/2697
  - [x] https://github.com/thematters/matters-web/issues/2707
  - [x] https://github.com/thematters/matters-web/issues/2708
  - [x] https://github.com/thematters/matters-web/issues/2709
  - [x] https://github.com/thematters/matters-web/issues/2717
  - [x] https://github.com/thematters/matters-web/issues/2718
  - [x] https://github.com/thematters/matters-server/issues/2771
  - [x] https://github.com/thematters/matters-email/issues/160
  - [x] https://github.com/thematters/matters-server/issues/2807
  - [x] https://github.com/thematters/matters-web/issues/2802
  
### Stage 3
- Wallet renew
  - [x] https://github.com/thematters/matters-web/issues/2866
 
- Update wallet login instruction
  - [x] https://github.com/thematters/matters-web/issues/2858
  - [x] https://github.com/thematters/matters-web/issues/2859
