### ISSUE TITLE
Retention Emails

### ISSUE THREAD

**Issue by devformatters** [thematters/developer-resource#129]
## Roadmap
- Study email related data (click and open)
- Setup a rule for sending

### Stage 1
- Research
  - [x] [[Analytics] Daily summary mail data sync #12](https://github.com/thematters/matters-analytics/issues/12)
  - [x] [[Analytics] Daily summary click tracking investigation and solution #13](https://github.com/thematters/matters-analytics/issues/13)
  - [x] [[Analytics] Daily summary mail analysis #11](https://github.com/thematters/matters-analytics/issues/11)

### Stage 2
- Design
  - https://github.com/thematters/matters-server/issues/2786

- Implementation
  - https://github.com/thematters/matters-server/issues/2787
  - https://github.com/thematters/matters-server/issues/2788
  - https://github.com/thematters/matters-email/issues/159

- Analytics
  - https://github.com/thematters/matters-server/issues/2790

**Comment by devformatters** [comment]
We've done some research. But the implementation requires review and rearrangement. Thus, close it.
