### ISSUE TITLE
Security: Beskar

### ISSUE THREAD

**Issue by robertu7** [thematters/developer-resource#137]
### Introduction
In late July 2022, both matters.news website and API faced large-scale DDoS attacks, exposed that our traffic management is immature.

In this epic, we focus on the network security, scanning the possible weak points and mitigating them.

### Roadmap
* :arrow_right: Netowrk
* Data

### Tasks
- [x] https://github.com/thematters/developer-resource/issues/142
- [x] https://github.com/thematters/developer-resource/issues/139
- [x] https://github.com/thematters/developer-resource/issues/143
- [x] https://github.com/thematters/developer-resource/issues/144
- [ ] ~https://github.com/thematters/developer-resource/issues/145~

**Comment by robertu7** [comment]
closed since #145 is stagnant, will assign to another Epic if needed
