### ISSUE TITLE
[Cloudflare] bypass traffic from verified bots and SSR servers

### ISSUE THREAD

**Issue by robertu7** [thematters/developer-resource#143]
### Introduction
matters.news client-side servers are hosted on Elastic Beanstalk (EB), and EC2 instances under EB control are changing (IP addresses) by auto-scaling.

Since Cloudflare could block these requests from client-side servers to API servers, SSR (Next.js Server-side Rendering) may be broken and affect SEO and social sharing. 

Currently, we set a rule to whitelist IPs of these client-side servers and [verified bot](https://radar.cloudflare.com/verified-bots), then bypass their requests to avoid being blocked. We need a better solution since IPs are changing as mentioned above.

### Tasks
- [ ] Research and provide a better solution to `bypass` traffic from verified bots and SSR servers;;
- [ ] Setup Cloudflare WAF rules;
- [ ] Related code changes from client-side;

### Discussion
* https://mattersnews.slack.com/archives/GA0R09FHN/p1659492188999119?thread_ts=1648995029.849469&cid=GA0R09FHN
* https://mattersnews.slack.com/archives/GA0R09FHN/p1659495154892539?thread_ts=1648995029.849469&cid=GA0R09FHN

### Related Resouces
* Elastic Beanstlak: [matters-client-develop](https://ap-southeast-1.console.aws.amazon.com/elasticbeanstalk/home?region=ap-southeast-1#/environment/dashboard?applicationName=matters-stage&environmentId=e-4mp4dq5viz), [matters-client-prod](https://ap-southeast-1.console.aws.amazon.com/elasticbeanstalk/home?region=ap-southeast-1#/environment/dashboard?applicationName=matters-prod&environmentId=e-rzivgjxtmx);
* Cloudflare WAF rule: [allow-whitelist](https://dash.cloudflare.com/757aaed316df635d8deb63859258808c/matters.news/security/waf/firewall-rules/c2da1e3ad1eb42188f0542ad347d3ad1);

### Refs
* [How do I assign a static source IP address for all instances in a load-balanced Elastic Beanstalk environment?](https://aws.amazon.com/premiumsupport/knowledge-center/elastic-beanstalk-static-IP-address/)

---

![Image](https://user-images.githubusercontent.com/4065233/183824926-b1bc1f47-d88a-4bfd-8dcc-505fd8392e9e.png)
