### ISSUE TITLE
Ruleset for DDoS

### ISSUE THREAD

**Issue by robertu7** [thematters/developer-resource#145]
### Tasks
- [ ] Ruleset for normal traffic;
- [ ] Ruleset for DDoS;
  - [ ] Specific rules for API server 
- [ ] Shared rulesets with community and Livid;

**Comment by robertu7** [comment]
https://www.cloudflare.com/lp/api-shield-enterprise-form/

**Comment by robertu7** [comment]
https://www.cloudflare.com/products/bot-management/

**Comment by robertu7** [comment]
Will reorg this ticket in Epic https://github.com/thematters/developer-resource/issues/242
