### ISSUE TITLE
Serve Next.js static assets under matters.news with Cloudflare CDN

### ISSUE THREAD

**Issue by robertu7** [thematters/developer-resource#146]
### Description
Prior to the migration of Cloudflare, Next.js static assets under matters.news are routed to S3 in Cloudfront, otherwise will hit the SSR server. We should do the same on Cloudflare.

### Tasks
- [x] `matters.news/_next/*` -> `assets-next.matters/_next/*`;
- [x] `web-develop.matters.news/_next/*` -> `assets-next-develop.matters/_next/*`;
- [x] add [`assetPrefix`](https://nextjs.org/docs/api-reference/next.config.js/cdn-support-with-asset-prefix);

**Comment by devformatters** [comment]
Shipped. So, close this one.
