### ISSUE TITLE
Support feedback

### ISSUE THREAD

**Issue by devformatters** [thematters/developer-resource#159]
## Roadmap
- [Product doc](https://paper.dropbox.com/doc/Matters--BqdxffYuRPBH7Ql~Sg7Z8ssWAg-3lhxiAzEnwkCA6SaphWXY)

### Stage 1

- Backend
  - [ ] https://github.com/thematters/matters-server/issues/2822
  - [ ] https://github.com/thematters/matters-server/issues/2825
  - [ ] https://github.com/thematters/matters-email/issues/161

- UIs
  - [ ] https://github.com/thematters/matters-web/issues/2808
  - [ ] https://github.com/thematters/matters-web/issues/2809
  - [ ] https://github.com/thematters/matters-web/issues/2810
