### ISSUE TITLE
AA survey

### ISSUE THREAD

**Issue by devformatters** [thematters/developer-resource#165]
### Tasks
- [ ] discuss and sort out a solution for users who have not connected wallet but can still accept USDT support
- [ ] output a documentation about entire solution
- [ ] (maybe) draft design of new smart contract

**Comment by devformatters** [comment]
Since we walked through all possible solution, close this survey tasks. I'll see if we need an new issue after call.
