### ISSUE TITLE
Matters.Town Setup (4/17)

### ISSUE THREAD

**Issue by devformatters** [thematters/developer-resource#207]
### Tasks
- [x] Clone matters-web and matters-server
    - [x] Revise **matters-web** & **matters-server** codebases (new branch & CI/CD)
    - [x] AWS: Certificate Manager (ACM) & [ElasticBeanstalk](https://github.com/thematters/matters-server/issues/2707) (EB)
- [x] Setup DNS & Cloudflare configs
- [x] Setup mail service (G Suite)
  - [x] [Doc](https://support.google.com/a/answer/7502379?hl=en#zippy=%2Csend-and-receive-messages-with-your-alternate-email-address%2Cmore-about-user-alias-domains-secondary-domains)
- [x]  Service confirmation
    - [x]  Website
    - [x]  API
    - [x]  Mail Service
    - [x]  SEO
- [x] Third-party services
    - [x] Inform Google Search Console
    - [x] Inform LikeCoin
    - [x] CORS: Alchemy & Google reCAPTCHA
    - [x] Stripe: top, payout, subscription

### References
- [Domain Migration Plan](https://www.notion.so/matterslab/Migrate-matters-news-to-matters-one-3673d16401f34f5e89a92a6fc8780426?pvs=4)

**Comment by tx0c** [comment]
update to use Matters.Town
