### ISSUE TITLE
Matters.News Redirection (4/20)

### ISSUE THREAD

**Issue by devformatters** [thematters/developer-resource#208]
### Tasks
- [x] Cloudflare Redirection
- [ ] Revise peripheral codebases to change the domain name
  - [x] matters-email 
  - [x] matters-lab-svelte-site 
  - [x] logbook 
  - [ ] ~ipns-site-generator~ (convert to a single issue)
  - [x] thespace-landing-page
- [x] Service confirmation
    - [x] Website
    - [x] API
    - [x] Mail Service
    - [x] SEO

### References
- [Domain Migration Doc](https://www.notion.so/matterslab/Migrate-matters-news-to-matters-one-3673d16401f34f5e89a92a6fc8780426)

**Comment by devformatters** [comment]
@robertu7 According to notion doc, what do you mean `service confirmation` here? It's a checklist after redirection or others?
