### ISSUE TITLE
Epic: Spam Detection

### ISSUE THREAD

**Issue by robertu7** [thematters/developer-resource#239]
### Description

As a content moderator, reducing spam is part of my responsibilities, I want authors who publish good content to be found more easily by interested readers, so that the community can become more active. 

### Stories
- [x] https://github.com/thematters/developer-resource/issues/280
- [x] https://github.com/thematters/developer-resource/issues/281
- [x] https://github.com/thematters/developer-resource/issues/472

**Comment by devformatters** [comment]
### Previously created tasks
- https://github.com/thematters/developer-resource/issues/236
- https://github.com/thematters/developer-resource/issues/238
