### ISSUE TITLE
User profile cover changes

### ISSUE THREAD

**Issue by devformatters** [thematters/developer-resource#265]
### Tasks
- Frontend
  - [ ] don't show default cover if not set up
  - [ ] allow user to remove cover

- Backend
  - [ ] API for remove user profile cover

### References
- [design](https://www.figma.com/file/nOzKx4pxuhhxdx1VzDJNfF/%E5%80%8B%E4%BA%BA%E9%A0%81-%26-%E9%81%B8%E9%9B%86?type=design&node-id=4160-14417&mode=design&t=GYr0J31QZVa717JG-0)
