### ISSUE TITLE
Epic: Up-To-Date Dependencies

### ISSUE THREAD

**Issue by robertu7** [thematters/developer-resource#270]
### Description
TODO 

### Stories
(~36 - 49)
- [x] https://github.com/thematters/matters-web/issues/3846 (5)
- [x] https://github.com/thematters/matters-server/issues/3622 (5)
- [x] https://github.com/thematters/matters-web/issues/3431 (13)
- [x] https://github.com/thematters/matters-web/issues/3430 (13)
- [x] https://github.com/thematters/matters-server/issues/3372 (5)
- [x] https://github.com/thematters/matters-server/issues/3246 (8)
