### ISSUE TITLE
Epic: Frontend Unit Testing

### ISSUE THREAD

**Issue by robertu7** [thematters/developer-resource#271]
### Description

As a developer, I want to deliver high quality software with the product requirements and standards, so that I can focus more on development instead of bugfixing;

### Stories
- [x] Setup;
- [x] https://github.com/thematters/developer-resource/issues/276
- [x] https://github.com/thematters/developer-resource/issues/277
- [x] https://github.com/thematters/developer-resource/issues/279
