### ISSUE TITLE
Post-validation of migrated images

### ISSUE THREAD

**Issue by robertu7** [thematters/developer-resource#294]
### Tasks
- [ ] Confirm solution to validate all migrated images: HEAD request or API request?
- [ ] Validation: how many images were missing?
- [ ] ~~Fix missing images~~

**Comment by devformatters** [comment]
According to meeting sync, it's still migrating. Do review in the next week.

**Comment by tx0c** [comment]
migration all done; results ~2000 images need client-side pre-process'ing of another round migration.

1. image size too big;     => shrink down
1. image dimension too big;     => shrink down
2. gif
