### ISSUE TITLE
(+8) Comment Drawer -- content

### ISSUE THREAD

**Issue by pitb2022** [thematters/developer-resource#337]
### Todos
 - [ ] New style of comment input
	 - [ ] Desktop
	 - [ ] Mobile
 - [ ] Visitor mode of comment input
 - [ ] Empty comment feed
	 - [ ] Desktop
	 - [ ] Mobile
 - [ ] New style of comment feed
 - [ ] Visitor mode of comment feed (https://www.figma.com/file/gs3w7fKdHqk9u1nnDxPYlZ/%E4%BD%9C%E5%93%81%E9%A0%81?node-id=840%3A46757&mode=dev)
 - [ ] pinned comment logic ()
 - [ ] New style of rich text expand
 - [ ] Secondary comment input opening logic (https://www.figma.com/file/gs3w7fKdHqk9u1nnDxPYlZ/%E4%BD%9C%E5%93%81%E9%A0%81?node-id=982%3A69293&mode=dev)

### Related
- https://github.com/thematters/matters-web/issues/4179

---

### Story
- https://github.com/thematters/developer-resource/issues/319
