### ISSUE TITLE
Setup Lambda API endpoint

### ISSUE THREAD

**Issue by gary02** [thematters/developer-resource#471]
### Tasks

- [x] setup S3 bucket for model
- [x] setup lambda
- [x] setup API gateway to above lambda
- [x] using [AWS CloudFormation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/Welcome.html)

---
### Story
- https://github.com/thematters/developer-resource/issues/472

**Comment by gary02** [comment]
https://github.com/thematters/spam-detection-serverless
